class LdapConfig():

    def __init__(self):
        self.groups = ['QLIKSENSE_MARKETING_USERS',
        'QLIKSENSE_MARKETING_LOGINS',
        'QLIKSENSE_MARKETING_ADMINS',
        'QLIKSENSE_MARKETING_DEV',
        'QLIKSENSE_MARKETING_ALL_STREAMS',
        'QLIKVIEW_MKTG_GEO_ALL',
        'QLIKVIEW_GEO_APAC',
        'QLIKVIEW_GEO_EMEA',
        'QLIKVIEW_GEO_LATAM',
        'QLIKVIEW_GEO_NACOMM',
        'QLIKVIEW_GEO_NAPS',
        'QLIKSENSE_ABM',
        'QLIKSENSE_GEO_APAC_DEV',
        'QLIKSENSE_GEO_APAC_DEV_STREAM',
        'QLIKSENSE_GEO_EMEA_DEV',
        'QLIKSENSE_GEO_EMEA_DEV_STREAM',
        'QLIKSENSE_GEO_LATAM_DEV',
        'QLIKSENSE_GEO_LATAM_DEV_STREAM',
        'QLIKSENSE_GEO_NA_DEV',
        'QLIKSENSE_GEO_NA_DEV_STREAM']